//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW.Models
{
    public class User
    {
        public string Username { get; internal set; }
        public string Password { get; internal set; }
        public string Role { get; internal set; }
    }
}